# Generated by Django 3.1.2 on 2020-10-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='Image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
