# Generated by Django 3.0.3 on 2020-02-21 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(max_length=5, null=True)),
                ('residence', models.CharField(max_length=50, null=True)),
                ('freelance', models.CharField(choices=[('Avalibale', 'Available'), ('Note Available', 'Not Available')], max_length=50, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.Service')),
            ],
        ),
    ]
