# Generated by Django 3.0.3 on 2020-02-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20200221_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
