# Generated by Django 3.0.3 on 2020-02-21 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20200221_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='services',
        ),
        migrations.AddField(
            model_name='resume',
            name='services',
            field=models.ManyToManyField(null=True, to='Home.Service'),
        ),
    ]
