# Generated by Django 3.0.3 on 2020-02-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20200221_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
