# Generated by Django 3.0.5 on 2020-04-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_post_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(null=True),
        ),
    ]
